// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xubillqzhmicpubjzaqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1YmlsbHF6aG1pY3B1Ymp6YXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMzAxOTcsImV4cCI6MjA1NDkwNjE5N30.2qjDBhuRCXSXq6iPL3h_dot6yEvgMISCUt-hmt_97qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);